name: CI

on:
  push:
    branches: [develop]
  repository_dispatch:
    types: [trigger-ci-workflow]
    branches: [develop]

env:
  FORCE_COLOR: true
  NODE_VERSION: 18

jobs:
  build:
    name: Build Bot
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event.action != 'repository_dispatch' }}

      - uses: actions/checkout@v3
        if: ${{ github.event.action == 'repository_dispatch' }}
        with:
          ref: ${{ github.event.client_payload.sha }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Run Linter
        run: yarn lint

      - name: Run Tests
        run: yarn test

      - name: Create Release
        if: success() && github.ref == 'refs/heads/develop'
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
